// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topicmanage.proto

package topicproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConnectNumRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectNumRequest) Reset()         { *m = GetConnectNumRequest{} }
func (m *GetConnectNumRequest) String() string { return proto.CompactTextString(m) }
func (*GetConnectNumRequest) ProtoMessage()    {}
func (*GetConnectNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_dfe7ee166aad9654, []int{0}
}
func (m *GetConnectNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectNumRequest.Unmarshal(m, b)
}
func (m *GetConnectNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectNumRequest.Marshal(b, m, deterministic)
}
func (dst *GetConnectNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectNumRequest.Merge(dst, src)
}
func (m *GetConnectNumRequest) XXX_Size() int {
	return xxx_messageInfo_GetConnectNumRequest.Size(m)
}
func (m *GetConnectNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectNumRequest proto.InternalMessageInfo

func (m *GetConnectNumRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type GetConnectNumResponse struct {
	Number               int64    `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectNumResponse) Reset()         { *m = GetConnectNumResponse{} }
func (m *GetConnectNumResponse) String() string { return proto.CompactTextString(m) }
func (*GetConnectNumResponse) ProtoMessage()    {}
func (*GetConnectNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_dfe7ee166aad9654, []int{1}
}
func (m *GetConnectNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectNumResponse.Unmarshal(m, b)
}
func (m *GetConnectNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectNumResponse.Marshal(b, m, deterministic)
}
func (dst *GetConnectNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectNumResponse.Merge(dst, src)
}
func (m *GetConnectNumResponse) XXX_Size() int {
	return xxx_messageInfo_GetConnectNumResponse.Size(m)
}
func (m *GetConnectNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectNumResponse proto.InternalMessageInfo

func (m *GetConnectNumResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*GetConnectNumRequest)(nil), "topicproto.GetConnectNumRequest")
	proto.RegisterType((*GetConnectNumResponse)(nil), "topicproto.GetConnectNumResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopicServiceClient is the client API for TopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicServiceClient interface {
	GetConnectNum(ctx context.Context, in *GetConnectNumRequest, opts ...grpc.CallOption) (*GetConnectNumResponse, error)
}

type topicServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopicServiceClient(cc *grpc.ClientConn) TopicServiceClient {
	return &topicServiceClient{cc}
}

func (c *topicServiceClient) GetConnectNum(ctx context.Context, in *GetConnectNumRequest, opts ...grpc.CallOption) (*GetConnectNumResponse, error) {
	out := new(GetConnectNumResponse)
	err := c.cc.Invoke(ctx, "/topicproto.TopicService/GetConnectNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicServiceServer is the server API for TopicService service.
type TopicServiceServer interface {
	GetConnectNum(context.Context, *GetConnectNumRequest) (*GetConnectNumResponse, error)
}

func RegisterTopicServiceServer(s *grpc.Server, srv TopicServiceServer) {
	s.RegisterService(&_TopicService_serviceDesc, srv)
}

func _TopicService_GetConnectNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectNumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetConnectNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicproto.TopicService/GetConnectNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetConnectNum(ctx, req.(*GetConnectNumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topicproto.TopicService",
	HandlerType: (*TopicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnectNum",
			Handler:    _TopicService_GetConnectNum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topicmanage.proto",
}

func init() { proto.RegisterFile("topicmanage.proto", fileDescriptor_topicmanage_dfe7ee166aad9654) }

var fileDescriptor_topicmanage_dfe7ee166aad9654 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc9, 0x2f, 0xc8,
	0x4c, 0xce, 0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02,
	0x0b, 0x81, 0xd9, 0x4a, 0x3a, 0x5c, 0x22, 0xee, 0xa9, 0x25, 0xce, 0xf9, 0x79, 0x79, 0xa9, 0xc9,
	0x25, 0x7e, 0xa5, 0xb9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x21,
	0x20, 0x55, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x92, 0x3e, 0x97, 0x28, 0x9a,
	0xea, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0x36, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4,
	0x22, 0xb0, 0x7a, 0xe6, 0x20, 0x28, 0xcf, 0x28, 0x8d, 0x8b, 0x07, 0xac, 0x33, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0x28, 0x8c, 0x8b, 0x17, 0xc5, 0x00, 0x21, 0x05, 0x3d, 0x84, 0x63, 0xf4,
	0xb0, 0xb9, 0x44, 0x4a, 0x11, 0x8f, 0x0a, 0x88, 0xed, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x69, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x29, 0x51, 0x94, 0xee, 0x00, 0x00, 0x00,
}
