// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topicmanage.proto

package topicproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConnectNumRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectNumRequest) Reset()         { *m = GetConnectNumRequest{} }
func (m *GetConnectNumRequest) String() string { return proto.CompactTextString(m) }
func (*GetConnectNumRequest) ProtoMessage()    {}
func (*GetConnectNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{0}
}
func (m *GetConnectNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectNumRequest.Unmarshal(m, b)
}
func (m *GetConnectNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectNumRequest.Marshal(b, m, deterministic)
}
func (dst *GetConnectNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectNumRequest.Merge(dst, src)
}
func (m *GetConnectNumRequest) XXX_Size() int {
	return xxx_messageInfo_GetConnectNumRequest.Size(m)
}
func (m *GetConnectNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectNumRequest proto.InternalMessageInfo

func (m *GetConnectNumRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type GetConnectNumResponse struct {
	Number               int64    `protobuf:"varint,1,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConnectNumResponse) Reset()         { *m = GetConnectNumResponse{} }
func (m *GetConnectNumResponse) String() string { return proto.CompactTextString(m) }
func (*GetConnectNumResponse) ProtoMessage()    {}
func (*GetConnectNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{1}
}
func (m *GetConnectNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConnectNumResponse.Unmarshal(m, b)
}
func (m *GetConnectNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConnectNumResponse.Marshal(b, m, deterministic)
}
func (dst *GetConnectNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConnectNumResponse.Merge(dst, src)
}
func (m *GetConnectNumResponse) XXX_Size() int {
	return xxx_messageInfo_GetConnectNumResponse.Size(m)
}
func (m *GetConnectNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConnectNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConnectNumResponse proto.InternalMessageInfo

func (m *GetConnectNumResponse) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SubscribeTopicRequest struct {
	Topic                []string `protobuf:"bytes,1,rep,name=Topic,proto3" json:"Topic,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeTopicRequest) Reset()         { *m = SubscribeTopicRequest{} }
func (m *SubscribeTopicRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeTopicRequest) ProtoMessage()    {}
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{2}
}
func (m *SubscribeTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeTopicRequest.Unmarshal(m, b)
}
func (m *SubscribeTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeTopicRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeTopicRequest.Merge(dst, src)
}
func (m *SubscribeTopicRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeTopicRequest.Size(m)
}
func (m *SubscribeTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeTopicRequest proto.InternalMessageInfo

func (m *SubscribeTopicRequest) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *SubscribeTopicRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type SubscribeTopicResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeTopicResponse) Reset()         { *m = SubscribeTopicResponse{} }
func (m *SubscribeTopicResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeTopicResponse) ProtoMessage()    {}
func (*SubscribeTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{3}
}
func (m *SubscribeTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeTopicResponse.Unmarshal(m, b)
}
func (m *SubscribeTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeTopicResponse.Marshal(b, m, deterministic)
}
func (dst *SubscribeTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeTopicResponse.Merge(dst, src)
}
func (m *SubscribeTopicResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeTopicResponse.Size(m)
}
func (m *SubscribeTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeTopicResponse proto.InternalMessageInfo

type UnSubscribeTopicRequest struct {
	Topic                []string `protobuf:"bytes,1,rep,name=Topic,proto3" json:"Topic,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnSubscribeTopicRequest) Reset()         { *m = UnSubscribeTopicRequest{} }
func (m *UnSubscribeTopicRequest) String() string { return proto.CompactTextString(m) }
func (*UnSubscribeTopicRequest) ProtoMessage()    {}
func (*UnSubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{4}
}
func (m *UnSubscribeTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSubscribeTopicRequest.Unmarshal(m, b)
}
func (m *UnSubscribeTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSubscribeTopicRequest.Marshal(b, m, deterministic)
}
func (dst *UnSubscribeTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSubscribeTopicRequest.Merge(dst, src)
}
func (m *UnSubscribeTopicRequest) XXX_Size() int {
	return xxx_messageInfo_UnSubscribeTopicRequest.Size(m)
}
func (m *UnSubscribeTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSubscribeTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnSubscribeTopicRequest proto.InternalMessageInfo

func (m *UnSubscribeTopicRequest) GetTopic() []string {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *UnSubscribeTopicRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type UnSubscribeTopicResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnSubscribeTopicResponse) Reset()         { *m = UnSubscribeTopicResponse{} }
func (m *UnSubscribeTopicResponse) String() string { return proto.CompactTextString(m) }
func (*UnSubscribeTopicResponse) ProtoMessage()    {}
func (*UnSubscribeTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{5}
}
func (m *UnSubscribeTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSubscribeTopicResponse.Unmarshal(m, b)
}
func (m *UnSubscribeTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSubscribeTopicResponse.Marshal(b, m, deterministic)
}
func (dst *UnSubscribeTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSubscribeTopicResponse.Merge(dst, src)
}
func (m *UnSubscribeTopicResponse) XXX_Size() int {
	return xxx_messageInfo_UnSubscribeTopicResponse.Size(m)
}
func (m *UnSubscribeTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSubscribeTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnSubscribeTopicResponse proto.InternalMessageInfo

type PublishRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{6}
}
func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (dst *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(dst, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PublishResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topicmanage_c9d4a958c1b553ac, []int{7}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (dst *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(dst, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*GetConnectNumRequest)(nil), "topicproto.GetConnectNumRequest")
	proto.RegisterType((*GetConnectNumResponse)(nil), "topicproto.GetConnectNumResponse")
	proto.RegisterType((*SubscribeTopicRequest)(nil), "topicproto.SubscribeTopicRequest")
	proto.RegisterType((*SubscribeTopicResponse)(nil), "topicproto.SubscribeTopicResponse")
	proto.RegisterType((*UnSubscribeTopicRequest)(nil), "topicproto.UnSubscribeTopicRequest")
	proto.RegisterType((*UnSubscribeTopicResponse)(nil), "topicproto.UnSubscribeTopicResponse")
	proto.RegisterType((*PublishRequest)(nil), "topicproto.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "topicproto.PublishResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopicServiceClient is the client API for TopicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopicServiceClient interface {
	GetConnectNum(ctx context.Context, in *GetConnectNumRequest, opts ...grpc.CallOption) (*GetConnectNumResponse, error)
	SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (*SubscribeTopicResponse, error)
	UnSubscribeTopic(ctx context.Context, in *UnSubscribeTopicRequest, opts ...grpc.CallOption) (*UnSubscribeTopicResponse, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
}

type topicServiceClient struct {
	cc *grpc.ClientConn
}

func NewTopicServiceClient(cc *grpc.ClientConn) TopicServiceClient {
	return &topicServiceClient{cc}
}

func (c *topicServiceClient) GetConnectNum(ctx context.Context, in *GetConnectNumRequest, opts ...grpc.CallOption) (*GetConnectNumResponse, error) {
	out := new(GetConnectNumResponse)
	err := c.cc.Invoke(ctx, "/topicproto.TopicService/GetConnectNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (*SubscribeTopicResponse, error) {
	out := new(SubscribeTopicResponse)
	err := c.cc.Invoke(ctx, "/topicproto.TopicService/SubscribeTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) UnSubscribeTopic(ctx context.Context, in *UnSubscribeTopicRequest, opts ...grpc.CallOption) (*UnSubscribeTopicResponse, error) {
	out := new(UnSubscribeTopicResponse)
	err := c.cc.Invoke(ctx, "/topicproto.TopicService/UnSubscribeTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, "/topicproto.TopicService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopicServiceServer is the server API for TopicService service.
type TopicServiceServer interface {
	GetConnectNum(context.Context, *GetConnectNumRequest) (*GetConnectNumResponse, error)
	SubscribeTopic(context.Context, *SubscribeTopicRequest) (*SubscribeTopicResponse, error)
	UnSubscribeTopic(context.Context, *UnSubscribeTopicRequest) (*UnSubscribeTopicResponse, error)
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
}

func RegisterTopicServiceServer(s *grpc.Server, srv TopicServiceServer) {
	s.RegisterService(&_TopicService_serviceDesc, srv)
}

func _TopicService_GetConnectNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectNumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).GetConnectNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicproto.TopicService/GetConnectNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).GetConnectNum(ctx, req.(*GetConnectNumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_SubscribeTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).SubscribeTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicproto.TopicService/SubscribeTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).SubscribeTopic(ctx, req.(*SubscribeTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_UnSubscribeTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnSubscribeTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).UnSubscribeTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicproto.TopicService/UnSubscribeTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).UnSubscribeTopic(ctx, req.(*UnSubscribeTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopicService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topicproto.TopicService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopicService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topicproto.TopicService",
	HandlerType: (*TopicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnectNum",
			Handler:    _TopicService_GetConnectNum_Handler,
		},
		{
			MethodName: "SubscribeTopic",
			Handler:    _TopicService_SubscribeTopic_Handler,
		},
		{
			MethodName: "UnSubscribeTopic",
			Handler:    _TopicService_UnSubscribeTopic_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _TopicService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topicmanage.proto",
}

func init() { proto.RegisterFile("topicmanage.proto", fileDescriptor_topicmanage_c9d4a958c1b553ac) }

var fileDescriptor_topicmanage_c9d4a958c1b553ac = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0xdf, 0x4e, 0x5f, 0xab, 0x1e, 0x6a, 0xd4, 0x4b, 0x5b, 0xc3, 0xb8, 0x69, 0x47, 0x17,
	0x2e, 0x24, 0x82, 0xee, 0x04, 0x71, 0x61, 0x41, 0xba, 0x69, 0x25, 0x55, 0xc1, 0x95, 0x24, 0x61,
	0xd0, 0x50, 0xf3, 0x61, 0x32, 0xf1, 0x37, 0xfb, 0x33, 0xc4, 0x69, 0x8c, 0x4d, 0x8c, 0xd9, 0xb8,
	0x9b, 0x8f, 0x73, 0x9e, 0xcb, 0x3d, 0x07, 0xbb, 0x2a, 0x8a, 0x7d, 0x2f, 0x70, 0x42, 0xe7, 0x49,
	0x5a, 0x71, 0x12, 0xa9, 0x88, 0xa0, 0x9f, 0xf4, 0x59, 0x1c, 0xa3, 0x77, 0x2d, 0xd5, 0x55, 0x14,
	0x86, 0xd2, 0x53, 0xd3, 0x2c, 0xb0, 0xe5, 0x6b, 0x26, 0x53, 0x45, 0x3d, 0xac, 0xdd, 0x7e, 0xaa,
	0xcc, 0xd6, 0xb0, 0x75, 0xb4, 0x69, 0x2f, 0x2f, 0xe2, 0x04, 0xfd, 0x8a, 0x3a, 0x8d, 0xa3, 0x30,
	0x95, 0x34, 0x40, 0x67, 0x9a, 0x05, 0xae, 0x4c, 0xb4, 0xbe, 0x6d, 0xe7, 0x37, 0x71, 0x81, 0xfe,
	0x3c, 0x73, 0x53, 0x2f, 0xf1, 0x5d, 0xa9, 0x11, 0x35, 0xfc, 0x76, 0xc1, 0x27, 0x03, 0x6c, 0x12,
	0x9b, 0x4c, 0x8f, 0x64, 0x93, 0x58, 0x98, 0x18, 0x54, 0xed, 0xcb, 0x81, 0xe2, 0x12, 0x7b, 0x77,
	0xe1, 0x5f, 0xd0, 0x1c, 0xe6, 0x4f, 0x40, 0x0e, 0x3f, 0x87, 0x71, 0x93, 0xb9, 0x2f, 0x7e, 0xfa,
	0xdc, 0x18, 0x07, 0x11, 0xfe, 0x8f, 0x1d, 0xe5, 0x68, 0x6a, 0xd7, 0xd6, 0x67, 0x31, 0xc2, 0x76,
	0xe1, 0xcd, 0xc3, 0x31, 0xc0, 0x66, 0x0b, 0xed, 0xdc, 0xb0, 0xd9, 0x6c, 0x71, 0xfa, 0xce, 0xd0,
	0xd5, 0x80, 0xb9, 0x4c, 0xde, 0x7c, 0x4f, 0xd2, 0x3d, 0xb6, 0x4a, 0xb1, 0xd2, 0xd0, 0xfa, 0xae,
	0xc8, 0xaa, 0xeb, 0x87, 0x8f, 0x1a, 0x14, 0xf9, 0x16, 0xff, 0xe8, 0x01, 0x46, 0x79, 0x43, 0x2a,
	0xd9, 0x6a, 0xe3, 0xe3, 0xa2, 0x49, 0x52, 0xa0, 0x1f, 0xb1, 0x53, 0x8d, 0x8f, 0x0e, 0x56, 0x9d,
	0xbf, 0xb4, 0xc3, 0x0f, 0x9b, 0x45, 0xc5, 0x80, 0x31, 0xd6, 0xf3, 0x1c, 0x89, 0xaf, 0x5a, 0xca,
	0xc5, 0xf0, 0xfd, 0xda, 0xbf, 0x2f, 0x8a, 0xdb, 0xd1, 0x1f, 0x67, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x9c, 0xa5, 0xeb, 0x3c, 0x06, 0x03, 0x00, 0x00,
}
